spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      bindings:
        producer-out-0:
          destination: first-topic
        consumer-in-0:
          destination: first-topic
      kafka:
        binder:
          brokers: ${PLACE_HOLDER}
      binders:
        kafka:
          environment:
            spring:
              main:
                sources: com.azure.spring.cloud.autoconfigure.kafka.AzureKafkaSpringCloudStreamConfiguration
#  kafka:
#    properties:
#      sasl:
#        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required
#            username="$ConnectionString" password="${PLACE_HOLDER}";
#        mechanism: PLAIN
#      security:
#        protocol: SASL_SSL
  profiles:
    active: develop