spring:
  kafka:
    properties:
#      sasl:
#        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required
#            username="$ConnectionString" password="${PLACE_HOLDER}";
#        mechanism: PLAIN
      security:
        protocol: SASL_SSL
    bootstrap-servers: ${PLACE_HOLDER}.servicebus.windows.net:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  profiles:
    active: develop